-- WA Service PostgreSQL baseline.
-- Applied only through scripts/supabase-apply-baseline.js, inside one transaction.
-- Application tables intentionally use TEXT + CHECK instead of PostgreSQL ENUM
-- so future enum changes remain transactional and migration-friendly.

CREATE TABLE public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  description VARCHAR(255),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  auth_version INTEGER NOT NULL DEFAULT 0 CHECK (auth_version >= 0),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'locked')),
  last_login_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3)
);

CREATE TABLE public.role_permissions (
  role_id BIGINT NOT NULL,
  permission_id BIGINT NOT NULL,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE public.user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE public.sessions (
  session_id VARCHAR(128) PRIMARY KEY,
  expires BIGINT NOT NULL CHECK (expires >= 0),
  data TEXT
);

CREATE TABLE public.login_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  email_hash VARCHAR(64) NOT NULL,
  ip_address VARCHAR(45),
  was_successful BOOLEAN NOT NULL DEFAULT FALSE,
  failure_reason VARCHAR(64),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.password_reset_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ(3) NOT NULL,
  used_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT,
  actor_type VARCHAR(32) NOT NULL DEFAULT 'user',
  action VARCHAR(120) NOT NULL,
  entity_type VARCHAR(80),
  entity_id VARCHAR(100),
  before_data JSONB,
  after_data JSONB,
  request_id VARCHAR(64),
  ip_address VARCHAR(45),
  user_agent VARCHAR(512),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.whatsapp_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(64) NOT NULL,
  name VARCHAR(120) NOT NULL,
  phone_number VARCHAR(32),
  status TEXT NOT NULL DEFAULT 'idle' CHECK (status IN ('idle', 'initializing', 'awaiting_qr', 'ready', 'disconnected', 'error')),
  last_connected_at TIMESTAMPTZ(3),
  last_disconnected_at TIMESTAMPTZ(3),
  last_error_code VARCHAR(100),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.whatsapp_connection_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  whatsapp_account_id BIGINT NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  phone_e164 VARCHAR(20) NOT NULL,
  country_code VARCHAR(4) NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'invalid', 'blocked', 'opted_out')),
  wa_registration_status TEXT NOT NULL DEFAULT 'unknown' CHECK (wa_registration_status IN ('unknown', 'registered', 'not_registered', 'check_failed')),
  consent_status TEXT NOT NULL DEFAULT 'unknown' CHECK (consent_status IN ('unknown', 'granted', 'revoked')),
  consent_source VARCHAR(100),
  consent_at TIMESTAMPTZ(3),
  opted_out_at TIMESTAMPTZ(3),
  custom_fields JSONB,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ(3),
  wa_registration_checked_at TIMESTAMPTZ(3)
);

CREATE TABLE public.contact_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id BIGINT,
  type TEXT NOT NULL DEFAULT 'custom' CHECK (type IN ('university', 'faculty', 'study_program', 'custom')),
  code VARCHAR(32) NOT NULL,
  path_key VARCHAR(191) NOT NULL,
  name VARCHAR(150) NOT NULL,
  description VARCHAR(255),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.contact_group_members (
  contact_group_id BIGINT NOT NULL,
  contact_id BIGINT NOT NULL,
  PRIMARY KEY (contact_group_id, contact_id)
);

CREATE TABLE public.campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT,
  university_group_id BIGINT NOT NULL,
  faculty_group_id BIGINT,
  study_program_group_id BIGINT,
  operator_user_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'paused', 'completed', 'archived')),
  archived_from_status TEXT CHECK (archived_from_status IN ('draft', 'active', 'paused', 'completed')),
  created_by BIGINT,
  updated_by BIGINT,
  archived_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.contact_imports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT,
  original_filename VARCHAR(255) NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('processing', 'previewed', 'committed', 'failed')),
  verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending', 'running', 'completed', 'completed_with_errors')),
  total_count INTEGER NOT NULL DEFAULT 0 CHECK (total_count >= 0),
  valid_count INTEGER NOT NULL DEFAULT 0 CHECK (valid_count >= 0),
  invalid_count INTEGER NOT NULL DEFAULT 0 CHECK (invalid_count >= 0),
  duplicate_count INTEGER NOT NULL DEFAULT 0 CHECK (duplicate_count >= 0),
  error_summary JSONB,
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.contact_import_rows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_import_id BIGINT NOT NULL,
  row_number INTEGER NOT NULL CHECK (row_number >= 0),
  name VARCHAR(150),
  raw_phone VARCHAR(100),
  normalized_phone VARCHAR(20),
  student_number VARCHAR(64),
  entry_year SMALLINT CHECK (entry_year >= 0),
  raw_faculty VARCHAR(150),
  raw_study_program VARCHAR(150),
  email VARCHAR(254),
  graduation_period VARCHAR(30),
  university_group_id BIGINT,
  faculty_group_id BIGINT,
  study_program_group_id BIGINT,
  university_code VARCHAR(32),
  faculty_code VARCHAR(32),
  study_program_code VARCHAR(32),
  university_name_snapshot VARCHAR(150),
  faculty_name_snapshot VARCHAR(150),
  study_program_name_snapshot VARCHAR(150),
  status TEXT NOT NULL CHECK (status IN ('valid', 'invalid', 'duplicate')),
  grouping_status TEXT NOT NULL DEFAULT 'not_applicable' CHECK (grouping_status IN ('not_applicable', 'valid', 'invalid')),
  grouping_error_code VARCHAR(100),
  wa_registration_status TEXT NOT NULL DEFAULT 'not_applicable' CHECK (wa_registration_status IN ('not_applicable', 'pending', 'checking', 'registered', 'not_registered', 'check_failed')),
  reason VARCHAR(120),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  wa_check_attempts INTEGER NOT NULL DEFAULT 0 CHECK (wa_check_attempts >= 0),
  wa_check_available_at TIMESTAMPTZ(3),
  wa_checked_at TIMESTAMPTZ(3),
  wa_error_code VARCHAR(100),
  wa_locked_at TIMESTAMPTZ(3),
  wa_locked_by VARCHAR(100)
);

CREATE TABLE public.contact_academic_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id BIGINT NOT NULL,
  university_group_id BIGINT NOT NULL,
  faculty_group_id BIGINT NOT NULL,
  study_program_group_id BIGINT NOT NULL,
  student_number VARCHAR(64) NOT NULL,
  entry_year SMALLINT NOT NULL CHECK (entry_year >= 0),
  email VARCHAR(254),
  graduation_period VARCHAR(30),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.media_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_key VARCHAR(512) NOT NULL,
  original_filename VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  checksum_sha256 VARCHAR(64) NOT NULL,
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.message_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  body TEXT NOT NULL,
  variables JSONB,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'archived')),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.broadcasts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  campaign_id BIGINT,
  campaign_idempotency_key VARCHAR(100),
  campaign_delivery_type TEXT CHECK (campaign_delivery_type IN ('blast', 'reblast_no_reply', 'reblast_stalled')),
  campaign_target_session INTEGER CHECK (campaign_target_session >= 0),
  name VARCHAR(180) NOT NULL,
  whatsapp_account_id BIGINT NOT NULL,
  body_snapshot TEXT NOT NULL,
  media_asset_id BIGINT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'running', 'paused', 'completed', 'partially_failed', 'cancelled')),
  scheduled_at TIMESTAMPTZ(3),
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  total_count INTEGER NOT NULL DEFAULT 0 CHECK (total_count >= 0),
  queued_count INTEGER NOT NULL DEFAULT 0 CHECK (queued_count >= 0),
  sent_count INTEGER NOT NULL DEFAULT 0 CHECK (sent_count >= 0),
  failed_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_count >= 0),
  skipped_count INTEGER NOT NULL DEFAULT 0 CHECK (skipped_count >= 0),
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  whatsapp_account_id BIGINT NOT NULL,
  contact_id BIGINT,
  broadcast_id BIGINT,
  campaign_id BIGINT,
  recipient_phone_e164 VARCHAR(20) NOT NULL,
  message_type TEXT NOT NULL DEFAULT 'text' CHECK (message_type IN ('text', 'image', 'document')),
  body TEXT NOT NULL,
  media_asset_id BIGINT,
  source TEXT NOT NULL CHECK (source IN ('dashboard', 'broadcast', 'api', 'campaign')),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'queued', 'processing', 'sent', 'failed', 'cancelled')),
  scheduled_at TIMESTAMPTZ(3),
  sent_at TIMESTAMPTZ(3),
  failed_at TIMESTAMPTZ(3),
  external_message_id VARCHAR(255),
  idempotency_key VARCHAR(100),
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.broadcast_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broadcast_id BIGINT NOT NULL,
  contact_id BIGINT,
  message_id BIGINT,
  recipient_phone_e164 VARCHAR(20) NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'queued', 'sent', 'failed', 'skipped')),
  skip_reason VARCHAR(100)
);

CREATE TABLE public.message_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  error_code VARCHAR(100),
  metadata JSONB,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.message_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reserved', 'processing', 'completed', 'failed', 'cancelled')),
  available_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_at TIMESTAMPTZ(3),
  locked_by VARCHAR(100),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts >= 0),
  last_error_code VARCHAR(100),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.incoming_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  contact_id BIGINT,
  from_phone VARCHAR(32) NOT NULL,
  from_name VARCHAR(255),
  body TEXT,
  has_media BOOLEAN NOT NULL DEFAULT FALSE,
  media_type VARCHAR(50),
  wa_message_id VARCHAR(255),
  quoted_wa_message_id VARCHAR(255),
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  received_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  session_number INTEGER CHECK (session_number >= 0)
);

CREATE TABLE public.api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  key_prefix VARCHAR(16) NOT NULL,
  key_hash VARCHAR(64) NOT NULL,
  scopes JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  expires_at TIMESTAMPTZ(3),
  last_used_at TIMESTAMPTZ(3),
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.webhooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url VARCHAR(2048) NOT NULL,
  signing_secret_encrypted TEXT NOT NULL,
  subscribed_events JSONB NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  created_by BIGINT,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.webhook_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_id BIGINT NOT NULL,
  event_name VARCHAR(120) NOT NULL,
  payload JSONB NOT NULL,
  response_status INTEGER CHECK (response_status >= 0),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  next_retry_at TIMESTAMPTZ(3),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.api_request_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_key_id BIGINT,
  request_id VARCHAR(64) NOT NULL,
  method VARCHAR(10) NOT NULL,
  endpoint VARCHAR(255) NOT NULL,
  response_status INTEGER NOT NULL CHECK (response_status >= 0),
  duration_ms INTEGER NOT NULL CHECK (duration_ms >= 0),
  ip_address VARCHAR(45),
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.qa_session_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_number INTEGER NOT NULL CHECK (session_number >= 0),
  title VARCHAR(255) NOT NULL,
  question_text TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.campaign_contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT NOT NULL,
  contact_id BIGINT NOT NULL,
  source_import_id BIGINT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'excluded', 'completed')),
  exclusion_reason VARCHAR(100),
  added_by BIGINT,
  added_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  excluded_at TIMESTAMPTZ(3),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.campaign_questionnaires (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  campaign_id BIGINT NOT NULL,
  version INTEGER NOT NULL CHECK (version >= 0),
  name VARCHAR(180) NOT NULL,
  is_current BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.campaign_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  campaign_id BIGINT NOT NULL,
  questionnaire_id BIGINT,
  position INTEGER NOT NULL CHECK (position >= 0),
  title VARCHAR(180) NOT NULL,
  question_text TEXT NOT NULL,
  answer_type TEXT NOT NULL DEFAULT 'choice' CHECK (answer_type IN ('free_text', 'choice')),
  next_question_id BIGINT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.campaign_question_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id VARCHAR(36) NOT NULL,
  campaign_question_id BIGINT NOT NULL,
  position INTEGER NOT NULL CHECK (position >= 0),
  answer_text VARCHAR(500) NOT NULL,
  action_type TEXT NOT NULL DEFAULT 'next' CHECK (action_type IN ('next', 'goto', 'review', 'complete')),
  next_question_id BIGINT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.campaign_contact_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_contact_id BIGINT NOT NULL,
  current_session_number INTEGER NOT NULL DEFAULT 0 CHECK (current_session_number >= 0),
  current_question_id BIGINT,
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'in_progress', 'review_pending_details', 'completed', 'stopped', 'needs_review')),
  review_fields JSONB,
  last_incoming_message_id BIGINT,
  last_outbound_message_id BIGINT,
  started_at TIMESTAMPTZ(3),
  completed_at TIMESTAMPTZ(3),
  reset_at TIMESTAMPTZ(3),
  reset_count INTEGER NOT NULL DEFAULT 0 CHECK (reset_count >= 0),
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.campaign_incoming_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incoming_message_id BIGINT NOT NULL,
  campaign_id BIGINT NOT NULL,
  campaign_contact_id BIGINT,
  campaign_question_id BIGINT,
  campaign_question_option_id BIGINT,
  attribution_method TEXT NOT NULL CHECK (attribution_method IN ('quoted_message', 'single_active_campaign', 'latest_outbound', 'manual')),
  interaction_type TEXT NOT NULL DEFAULT 'session_answer' CHECK (interaction_type IN ('session_answer', 'reblast_confirmation', 'start_command', 'review_detail')),
  reblast_decision TEXT CHECK (reblast_decision IN ('accepted', 'declined', 'invalid')),
  reply_to_message_id BIGINT,
  attributed_by BIGINT,
  attributed_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.application_settings (
  setting_key VARCHAR(120) PRIMARY KEY,
  value_type TEXT NOT NULL CHECK (value_type IN ('string', 'number', 'boolean', 'json')),
  setting_value TEXT NOT NULL,
  category VARCHAR(80) NOT NULL,
  updated_by BIGINT,
  updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Foreign keys are declared after every table exists to keep dependency order explicit.
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_role_id_foreign FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_permission_id_foreign FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_role_id_foreign FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE CASCADE;
ALTER TABLE public.login_attempts ADD CONSTRAINT login_attempts_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.password_reset_tokens ADD CONSTRAINT password_reset_tokens_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_actor_user_id_foreign FOREIGN KEY (actor_user_id) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.whatsapp_connection_events ADD CONSTRAINT whatsapp_connection_events_whatsapp_account_id_foreign FOREIGN KEY (whatsapp_account_id) REFERENCES public.whatsapp_accounts(id) ON DELETE CASCADE;
ALTER TABLE public.contact_groups ADD CONSTRAINT contact_groups_parent_fk FOREIGN KEY (parent_id) REFERENCES public.contact_groups(id) ON DELETE RESTRICT;
ALTER TABLE public.contact_group_members ADD CONSTRAINT contact_group_members_contact_group_id_foreign FOREIGN KEY (contact_group_id) REFERENCES public.contact_groups(id) ON DELETE CASCADE;
ALTER TABLE public.contact_group_members ADD CONSTRAINT contact_group_members_contact_id_foreign FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE;
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_university_group_id_foreign FOREIGN KEY (university_group_id) REFERENCES public.contact_groups(id) ON DELETE RESTRICT;
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_faculty_group_id_foreign FOREIGN KEY (faculty_group_id) REFERENCES public.contact_groups(id) ON DELETE RESTRICT;
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_study_program_group_id_foreign FOREIGN KEY (study_program_group_id) REFERENCES public.contact_groups(id) ON DELETE RESTRICT;
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_operator_user_id_foreign FOREIGN KEY (operator_user_id) REFERENCES public.users(id) ON DELETE RESTRICT;
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_updated_by_foreign FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.contact_imports ADD CONSTRAINT contact_imports_campaign_fk FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE RESTRICT;
ALTER TABLE public.contact_imports ADD CONSTRAINT contact_imports_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.contact_import_rows ADD CONSTRAINT contact_import_rows_contact_import_id_foreign FOREIGN KEY (contact_import_id) REFERENCES public.contact_imports(id) ON DELETE CASCADE;
ALTER TABLE public.contact_import_rows ADD CONSTRAINT contact_import_rows_university_fk FOREIGN KEY (university_group_id) REFERENCES public.contact_groups(id) ON DELETE SET NULL;
ALTER TABLE public.contact_import_rows ADD CONSTRAINT contact_import_rows_faculty_fk FOREIGN KEY (faculty_group_id) REFERENCES public.contact_groups(id) ON DELETE SET NULL;
ALTER TABLE public.contact_import_rows ADD CONSTRAINT contact_import_rows_program_fk FOREIGN KEY (study_program_group_id) REFERENCES public.contact_groups(id) ON DELETE SET NULL;
ALTER TABLE public.contact_academic_profiles ADD CONSTRAINT contact_academic_profiles_contact_id_foreign FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE;
ALTER TABLE public.contact_academic_profiles ADD CONSTRAINT contact_academic_profiles_university_group_id_foreign FOREIGN KEY (university_group_id) REFERENCES public.contact_groups(id) ON DELETE RESTRICT;
ALTER TABLE public.contact_academic_profiles ADD CONSTRAINT contact_academic_profiles_faculty_group_id_foreign FOREIGN KEY (faculty_group_id) REFERENCES public.contact_groups(id) ON DELETE RESTRICT;
ALTER TABLE public.contact_academic_profiles ADD CONSTRAINT contact_academic_profiles_study_program_group_id_foreign FOREIGN KEY (study_program_group_id) REFERENCES public.contact_groups(id) ON DELETE RESTRICT;
ALTER TABLE public.media_assets ADD CONSTRAINT media_assets_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.message_templates ADD CONSTRAINT message_templates_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.message_templates ADD CONSTRAINT message_templates_updated_by_foreign FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.broadcasts ADD CONSTRAINT broadcasts_campaign_fk FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE RESTRICT;
ALTER TABLE public.broadcasts ADD CONSTRAINT broadcasts_whatsapp_account_id_foreign FOREIGN KEY (whatsapp_account_id) REFERENCES public.whatsapp_accounts(id) ON DELETE RESTRICT;
ALTER TABLE public.broadcasts ADD CONSTRAINT broadcasts_media_asset_id_foreign FOREIGN KEY (media_asset_id) REFERENCES public.media_assets(id) ON DELETE SET NULL;
ALTER TABLE public.broadcasts ADD CONSTRAINT broadcasts_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_whatsapp_account_id_foreign FOREIGN KEY (whatsapp_account_id) REFERENCES public.whatsapp_accounts(id) ON DELETE RESTRICT;
ALTER TABLE public.messages ADD CONSTRAINT messages_contact_id_foreign FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_broadcast_id_foreign FOREIGN KEY (broadcast_id) REFERENCES public.broadcasts(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_campaign_fk FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE RESTRICT;
ALTER TABLE public.messages ADD CONSTRAINT messages_media_asset_id_foreign FOREIGN KEY (media_asset_id) REFERENCES public.media_assets(id) ON DELETE SET NULL;
ALTER TABLE public.messages ADD CONSTRAINT messages_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.broadcast_recipients ADD CONSTRAINT broadcast_recipients_broadcast_id_foreign FOREIGN KEY (broadcast_id) REFERENCES public.broadcasts(id) ON DELETE CASCADE;
ALTER TABLE public.broadcast_recipients ADD CONSTRAINT broadcast_recipients_contact_id_foreign FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.broadcast_recipients ADD CONSTRAINT broadcast_recipients_message_id_foreign FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE SET NULL;
ALTER TABLE public.message_events ADD CONSTRAINT message_events_message_id_foreign FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;
ALTER TABLE public.message_jobs ADD CONSTRAINT message_jobs_message_id_foreign FOREIGN KEY (message_id) REFERENCES public.messages(id) ON DELETE CASCADE;
ALTER TABLE public.incoming_messages ADD CONSTRAINT incoming_messages_contact_id_foreign FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.api_keys ADD CONSTRAINT api_keys_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.webhooks ADD CONSTRAINT webhooks_created_by_foreign FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.webhook_deliveries ADD CONSTRAINT webhook_deliveries_webhook_id_foreign FOREIGN KEY (webhook_id) REFERENCES public.webhooks(id) ON DELETE CASCADE;
ALTER TABLE public.api_request_logs ADD CONSTRAINT api_request_logs_api_key_id_foreign FOREIGN KEY (api_key_id) REFERENCES public.api_keys(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_contacts ADD CONSTRAINT campaign_contacts_campaign_id_foreign FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_contacts ADD CONSTRAINT campaign_contacts_contact_id_foreign FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_contacts ADD CONSTRAINT campaign_contacts_source_import_id_foreign FOREIGN KEY (source_import_id) REFERENCES public.contact_imports(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_contacts ADD CONSTRAINT campaign_contacts_added_by_foreign FOREIGN KEY (added_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_questionnaires ADD CONSTRAINT campaign_questionnaires_campaign_id_foreign FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_questions ADD CONSTRAINT campaign_questions_campaign_id_foreign FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_questions ADD CONSTRAINT campaign_questions_questionnaire_fk FOREIGN KEY (questionnaire_id) REFERENCES public.campaign_questionnaires(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_questions ADD CONSTRAINT campaign_questions_next_fk FOREIGN KEY (next_question_id) REFERENCES public.campaign_questions(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_question_options ADD CONSTRAINT campaign_question_options_campaign_question_id_foreign FOREIGN KEY (campaign_question_id) REFERENCES public.campaign_questions(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_question_options ADD CONSTRAINT campaign_question_options_next_fk FOREIGN KEY (next_question_id) REFERENCES public.campaign_questions(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_contact_progress ADD CONSTRAINT campaign_contact_progress_campaign_contact_id_foreign FOREIGN KEY (campaign_contact_id) REFERENCES public.campaign_contacts(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_contact_progress ADD CONSTRAINT campaign_progress_question_fk FOREIGN KEY (current_question_id) REFERENCES public.campaign_questions(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_contact_progress ADD CONSTRAINT campaign_contact_progress_last_incoming_message_id_foreign FOREIGN KEY (last_incoming_message_id) REFERENCES public.incoming_messages(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_contact_progress ADD CONSTRAINT campaign_contact_progress_last_outbound_message_id_foreign FOREIGN KEY (last_outbound_message_id) REFERENCES public.messages(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_incoming_messages ADD CONSTRAINT campaign_incoming_messages_incoming_message_id_foreign FOREIGN KEY (incoming_message_id) REFERENCES public.incoming_messages(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_incoming_messages ADD CONSTRAINT campaign_incoming_messages_campaign_id_foreign FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id) ON DELETE RESTRICT;
ALTER TABLE public.campaign_incoming_messages ADD CONSTRAINT campaign_incoming_messages_campaign_contact_id_foreign FOREIGN KEY (campaign_contact_id) REFERENCES public.campaign_contacts(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_incoming_messages ADD CONSTRAINT campaign_incoming_question_fk FOREIGN KEY (campaign_question_id) REFERENCES public.campaign_questions(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_incoming_messages ADD CONSTRAINT campaign_incoming_option_fk FOREIGN KEY (campaign_question_option_id) REFERENCES public.campaign_question_options(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_incoming_messages ADD CONSTRAINT campaign_incoming_reply_message_fk FOREIGN KEY (reply_to_message_id) REFERENCES public.messages(id) ON DELETE SET NULL;
ALTER TABLE public.campaign_incoming_messages ADD CONSTRAINT campaign_incoming_messages_attributed_by_foreign FOREIGN KEY (attributed_by) REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.application_settings ADD CONSTRAINT application_settings_updated_by_foreign FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL;

-- Unique business keys.
CREATE UNIQUE INDEX roles_name_unique ON public.roles (name);
CREATE UNIQUE INDEX permissions_code_unique ON public.permissions (code);
CREATE UNIQUE INDEX users_email_unique ON public.users (email);
CREATE UNIQUE INDEX password_reset_tokens_token_hash_unique ON public.password_reset_tokens (token_hash);
CREATE UNIQUE INDEX whatsapp_accounts_public_id_unique ON public.whatsapp_accounts (public_id);
CREATE UNIQUE INDEX contacts_phone_e164_unique ON public.contacts (phone_e164);
CREATE UNIQUE INDEX contact_groups_path_key_unique ON public.contact_groups (path_key);
CREATE UNIQUE INDEX contact_import_rows_contact_import_id_row_number_unique ON public.contact_import_rows (contact_import_id, row_number);
CREATE UNIQUE INDEX contact_academic_profile_contact_university_unique ON public.contact_academic_profiles (contact_id, university_group_id);
CREATE UNIQUE INDEX contact_academic_profile_university_nim_unique ON public.contact_academic_profiles (university_group_id, student_number);
CREATE UNIQUE INDEX media_assets_storage_key_unique ON public.media_assets (storage_key);
CREATE UNIQUE INDEX message_templates_name_unique ON public.message_templates (name);
CREATE UNIQUE INDEX broadcasts_public_id_unique ON public.broadcasts (public_id);
CREATE UNIQUE INDEX broadcasts_campaign_idempotency_unique ON public.broadcasts (campaign_id, campaign_idempotency_key);
CREATE UNIQUE INDEX messages_public_id_unique ON public.messages (public_id);
CREATE UNIQUE INDEX messages_source_idempotency_key_unique ON public.messages (source, idempotency_key);
CREATE UNIQUE INDEX broadcast_recipients_broadcast_phone_unique ON public.broadcast_recipients (broadcast_id, recipient_phone_e164);
CREATE UNIQUE INDEX message_jobs_message_id_unique ON public.message_jobs (message_id);
CREATE UNIQUE INDEX incoming_messages_public_id_unique ON public.incoming_messages (public_id);
CREATE UNIQUE INDEX api_keys_key_prefix_unique ON public.api_keys (key_prefix);
CREATE UNIQUE INDEX api_keys_key_hash_unique ON public.api_keys (key_hash);
CREATE UNIQUE INDEX qa_session_questions_session_number_unique ON public.qa_session_questions (session_number);
CREATE UNIQUE INDEX campaigns_public_id_unique ON public.campaigns (public_id);
CREATE UNIQUE INDEX campaign_contacts_unique ON public.campaign_contacts (campaign_id, contact_id);
CREATE UNIQUE INDEX campaign_questionnaires_public_id_unique ON public.campaign_questionnaires (public_id);
CREATE UNIQUE INDEX campaign_questionnaires_version_unique ON public.campaign_questionnaires (campaign_id, version);
CREATE UNIQUE INDEX campaign_questions_public_id_unique ON public.campaign_questions (public_id);
CREATE UNIQUE INDEX campaign_questions_version_position_unique ON public.campaign_questions (questionnaire_id, position);
CREATE UNIQUE INDEX campaign_question_options_public_id_unique ON public.campaign_question_options (public_id);
CREATE UNIQUE INDEX campaign_question_options_position_unique ON public.campaign_question_options (campaign_question_id, position);
CREATE UNIQUE INDEX campaign_contact_progress_campaign_contact_id_unique ON public.campaign_contact_progress (campaign_contact_id);
CREATE UNIQUE INDEX campaign_incoming_messages_incoming_message_id_unique ON public.campaign_incoming_messages (incoming_message_id);

-- Query-path indexes from the final MySQL schema.
CREATE INDEX users_status_deleted_at_index ON public.users (status, deleted_at);
CREATE INDEX sessions_expires_index ON public.sessions (expires);
CREATE INDEX login_attempts_email_hash_created_at_index ON public.login_attempts (email_hash, created_at);
CREATE INDEX login_attempts_ip_address_created_at_index ON public.login_attempts (ip_address, created_at);
CREATE INDEX password_reset_tokens_user_id_expires_at_index ON public.password_reset_tokens (user_id, expires_at);
CREATE INDEX audit_logs_actor_user_id_created_at_index ON public.audit_logs (actor_user_id, created_at);
CREATE INDEX audit_logs_entity_type_entity_id_index ON public.audit_logs (entity_type, entity_id);
CREATE INDEX audit_logs_action_created_at_index ON public.audit_logs (action, created_at);
CREATE INDEX whatsapp_accounts_status_index ON public.whatsapp_accounts (status);
CREATE INDEX whatsapp_connection_events_account_created_idx ON public.whatsapp_connection_events (whatsapp_account_id, created_at);
CREATE INDEX contacts_status_deleted_at_index ON public.contacts (status, deleted_at);
CREATE INDEX contacts_wa_registration_idx ON public.contacts (wa_registration_status, deleted_at);
CREATE INDEX contact_groups_hierarchy_idx ON public.contact_groups (parent_id, type, status);
CREATE INDEX contact_imports_campaign_status_idx ON public.contact_imports (campaign_id, status);
CREATE INDEX contact_import_rows_contact_import_status_idx ON public.contact_import_rows (contact_import_id, status);
CREATE INDEX contact_import_rows_grouping_idx ON public.contact_import_rows (contact_import_id, grouping_status);
CREATE INDEX contact_import_rows_wa_queue_idx ON public.contact_import_rows (wa_registration_status, wa_check_available_at);
CREATE INDEX contact_import_rows_wa_result_idx ON public.contact_import_rows (contact_import_id, wa_registration_status);
CREATE INDEX contact_academic_profile_scope_idx ON public.contact_academic_profiles (faculty_group_id, study_program_group_id);
CREATE INDEX contact_academic_profile_entry_year_idx ON public.contact_academic_profiles (entry_year);
CREATE INDEX message_templates_status_index ON public.message_templates (status);
CREATE INDEX broadcasts_status_scheduled_at_index ON public.broadcasts (status, scheduled_at);
CREATE INDEX broadcasts_campaign_status_idx ON public.broadcasts (campaign_id, status);
CREATE INDEX broadcasts_campaign_delivery_idx ON public.broadcasts (campaign_id, campaign_delivery_type, created_at);
CREATE INDEX messages_status_scheduled_at_index ON public.messages (status, scheduled_at);
CREATE INDEX messages_recipient_phone_created_at_idx ON public.messages (recipient_phone_e164, created_at);
CREATE INDEX messages_campaign_status_idx ON public.messages (campaign_id, status);
CREATE INDEX message_events_message_created_at_idx ON public.message_events (message_id, created_at);
CREATE INDEX message_jobs_status_available_at_index ON public.message_jobs (status, available_at);
CREATE INDEX message_jobs_locked_at_locked_by_index ON public.message_jobs (locked_at, locked_by);
CREATE INDEX incoming_messages_is_read_received_at_index ON public.incoming_messages (is_read, received_at);
CREATE INDEX incoming_messages_from_phone_index ON public.incoming_messages (from_phone);
CREATE INDEX incoming_messages_wa_message_id_index ON public.incoming_messages (wa_message_id);
CREATE INDEX incoming_messages_quoted_idx ON public.incoming_messages (quoted_wa_message_id);
CREATE INDEX incoming_messages_session_number_index ON public.incoming_messages (session_number);
CREATE INDEX webhook_deliveries_next_retry_attempts_idx ON public.webhook_deliveries (next_retry_at, attempts);
CREATE INDEX api_request_logs_api_key_created_at_idx ON public.api_request_logs (api_key_id, created_at);
CREATE INDEX campaigns_status_updated_idx ON public.campaigns (status, updated_at);
CREATE INDEX campaigns_operator_status_idx ON public.campaigns (operator_user_id, status);
CREATE INDEX campaigns_academic_scope_idx ON public.campaigns (university_group_id, faculty_group_id, study_program_group_id);
CREATE INDEX campaign_contacts_status_idx ON public.campaign_contacts (campaign_id, status);
CREATE INDEX campaign_questionnaires_current_idx ON public.campaign_questionnaires (campaign_id, is_current);
CREATE INDEX campaign_questions_active_idx ON public.campaign_questions (campaign_id, is_active, position);
CREATE INDEX campaign_questions_version_active_idx ON public.campaign_questions (questionnaire_id, is_active, position);
CREATE INDEX campaign_questions_next_idx ON public.campaign_questions (next_question_id);
CREATE INDEX campaign_question_options_next_idx ON public.campaign_question_options (next_question_id);
CREATE INDEX campaign_progress_status_idx ON public.campaign_contact_progress (status, current_session_number);
CREATE INDEX campaign_progress_question_idx ON public.campaign_contact_progress (current_question_id);
CREATE INDEX campaign_incoming_campaign_time_idx ON public.campaign_incoming_messages (campaign_id, attributed_at);
CREATE INDEX campaign_incoming_answer_idx ON public.campaign_incoming_messages (campaign_question_id, campaign_question_option_id);
CREATE INDEX campaign_incoming_interaction_idx ON public.campaign_incoming_messages (campaign_id, interaction_type, reblast_decision);
CREATE INDEX application_settings_category_index ON public.application_settings (category);

-- PostgreSQL does not auto-index foreign-key columns. These indexes mirror the
-- FK-supporting indexes that MySQL created automatically.
CREATE INDEX role_permissions_permission_id_foreign ON public.role_permissions (permission_id);
CREATE INDEX user_roles_role_id_foreign ON public.user_roles (role_id);
CREATE INDEX login_attempts_user_id_foreign ON public.login_attempts (user_id);
CREATE INDEX contact_group_members_contact_id_foreign ON public.contact_group_members (contact_id);
CREATE INDEX contact_imports_created_by_foreign ON public.contact_imports (created_by);
CREATE INDEX contact_import_rows_university_fk ON public.contact_import_rows (university_group_id);
CREATE INDEX contact_import_rows_faculty_fk ON public.contact_import_rows (faculty_group_id);
CREATE INDEX contact_import_rows_program_fk ON public.contact_import_rows (study_program_group_id);
CREATE INDEX contact_academic_profiles_study_program_fk_idx ON public.contact_academic_profiles (study_program_group_id);
CREATE INDEX media_assets_created_by_foreign ON public.media_assets (created_by);
CREATE INDEX message_templates_created_by_foreign ON public.message_templates (created_by);
CREATE INDEX message_templates_updated_by_foreign ON public.message_templates (updated_by);
CREATE INDEX broadcasts_whatsapp_account_id_foreign ON public.broadcasts (whatsapp_account_id);
CREATE INDEX broadcasts_media_asset_id_foreign ON public.broadcasts (media_asset_id);
CREATE INDEX broadcasts_created_by_foreign ON public.broadcasts (created_by);
CREATE INDEX messages_whatsapp_account_id_foreign ON public.messages (whatsapp_account_id);
CREATE INDEX messages_contact_id_foreign ON public.messages (contact_id);
CREATE INDEX messages_broadcast_id_foreign ON public.messages (broadcast_id);
CREATE INDEX messages_media_asset_id_foreign ON public.messages (media_asset_id);
CREATE INDEX messages_created_by_foreign ON public.messages (created_by);
CREATE INDEX broadcast_recipients_contact_id_foreign ON public.broadcast_recipients (contact_id);
CREATE INDEX broadcast_recipients_message_id_foreign ON public.broadcast_recipients (message_id);
CREATE INDEX incoming_messages_contact_id_foreign ON public.incoming_messages (contact_id);
CREATE INDEX api_keys_created_by_foreign ON public.api_keys (created_by);
CREATE INDEX webhooks_created_by_foreign ON public.webhooks (created_by);
CREATE INDEX webhook_deliveries_webhook_id_foreign ON public.webhook_deliveries (webhook_id);
CREATE INDEX campaigns_faculty_group_id_foreign ON public.campaigns (faculty_group_id);
CREATE INDEX campaigns_study_program_group_id_foreign ON public.campaigns (study_program_group_id);
CREATE INDEX campaigns_created_by_foreign ON public.campaigns (created_by);
CREATE INDEX campaigns_updated_by_foreign ON public.campaigns (updated_by);
CREATE INDEX campaign_contacts_contact_id_foreign ON public.campaign_contacts (contact_id);
CREATE INDEX campaign_contacts_source_import_id_foreign ON public.campaign_contacts (source_import_id);
CREATE INDEX campaign_contacts_added_by_foreign ON public.campaign_contacts (added_by);
CREATE INDEX campaign_progress_last_incoming_fk_idx ON public.campaign_contact_progress (last_incoming_message_id);
CREATE INDEX campaign_progress_last_outbound_fk_idx ON public.campaign_contact_progress (last_outbound_message_id);
CREATE INDEX campaign_incoming_contact_fk_idx ON public.campaign_incoming_messages (campaign_contact_id);
CREATE INDEX campaign_incoming_option_fk ON public.campaign_incoming_messages (campaign_question_option_id);
CREATE INDEX campaign_incoming_reply_message_fk ON public.campaign_incoming_messages (reply_to_message_id);
CREATE INDEX campaign_incoming_attributed_by_fk_idx ON public.campaign_incoming_messages (attributed_by);
CREATE INDEX application_settings_updated_by_foreign ON public.application_settings (updated_by);

-- Knex migration bookkeeping. Existing MySQL migration names are inserted by the
-- guarded apply script only after this SQL succeeds.
CREATE TABLE public.knex_migrations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  batch INTEGER,
  migration_time TIMESTAMPTZ
);

CREATE TABLE public.knex_migrations_lock (
  index INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  is_locked INTEGER
);

INSERT INTO public.knex_migrations_lock (is_locked) VALUES (0);

-- Supabase hardening: these server-side tables are not exposed to anon/authenticated
-- through PostgREST. The backend will later use a dedicated server database role.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_connection_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_import_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_academic_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcast_recipients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incoming_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_request_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qa_session_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_contact_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_questionnaires ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_question_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_incoming_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.application_settings ENABLE ROW LEVEL SECURITY;
